name: publish

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Format
      run: |
        $FLUTTER_HOME/bin/cache/dart-sdk/bin/dartfmt -l 80 -w .
    - name: Publish
      run: |
        flutter pub get
        echo "${{ secrets.PUB_CREDENTIALS }}" | base64 --decode > ~/.pub-cache/credentials.json
        pub publish --force
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
